server:
  port: 8081

spring:
  application:
    name: query
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  spring.jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update